baseUrl: "https://aldrinjenson.github.io"
languageCode: "en-us"
title: "Aldrin's Blog"
theme: "anubis"
paginate: 10
# disqusShortname: "yourdiscussshortname"
# googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 0
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 0

params:
  author: "Aldrin Jenson"
  email: aldrinjenson@gmail.com # used for microformats
  avatar: "/images/me.jpg" # used for microformats
  description: "CS undergrad from Kerala, India"
  # Uncomment if you need this
  # images:
  #   - images/me.jpg # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "02-01-2006"
  paginationSinglePost: true
  style: auto
  readMore: false
  disableSummary: false
  # utteranc.es support
  utterancesRepo: "" # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
    - id: github
      name: aldrinjenson
    - id: linkedin
      name: aldrinjenson
    - id: twitter
      name: aldrinjenson
    - id: medium
      name: aldrinjenson

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

canonifyURLs: true
