baseUrl: "aldrinjenson-github-io.vercel.app/"
languageCode: "en-us"
title: "Aldrin Jenson"
theme: "anubis"
paginate: 25
enableRobotsTXT: true
googleAnalytics: "G-J94XZYNB9C"

menu:
  main:
    - identifier: Home
      name: Home
      title: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 1
    - identifier: projects
      name: Projects
      title: Projects
      url: /projects/
      weight: 2
    # - identifier: Personal
    #   name: Personal
    #   title: Personal
    #   url: /personal/
    #   weight: 3

params:
  author: "Aldrin Jenson"
  email: aldrinjenson@gmail.com
  avatar: "/images/me.jpg"
  description: "CS undergrad from Kerala, India"
  dateFormat: "02-01-2006"
  paginationSinglePost: true
  style: auto
  readMore: false
  disableSummary: false
  utterancesRepo: "https://github.com/aldrinjenson/aldrinjenson.github."
  utterancesTheme: "github-dark"
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # utterancesIssue: ""
  utterancesLabel: "comment"
  # webmentions:
  #   url: https://yourdomain.com/webemntions/receive
  #   login: hugo-theme-anubis
  #   pingback: true
  social:
    - id: github
      name: aldrinjenson
    - id: linkedin
      name: aldrinjenson
    - id: twitter
      name: aldrinjenson
    - id: medium
      name: aldrinjenson
    - id: rss
      name: "index.xml"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

canonifyURLs: true
