baseUrl: "https://aldrinjenson.me/"
languageCode: "en-us"
title: "Aldrin's Blog"
theme: "github.com/Mitrichius/hugo-theme-anubis"
paginate: 6
enableRobotsTXT: true

menu:
  main:
    - identifier: posts
      name: Posts
      title: Posts
      url: /posts/
      weight: 1
    - identifier: projects
      name: Projects
      title: Projects
      url: /projects/
      weight: 2
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 3

params:
  author: "Aldrin Jenson"
  email: aldrinjenson@gmail.com # used for microformats
  avatar: "/images/me.jpg" # used for microformats
  description: "CS undergrad from Kerala, India"
  # Uncomment if you need this
  # images:
  #   - images/me.jpg # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "02-01-2006"
  paginationSinglePost: true
  style: auto
  readMore: false
  disableSummary: false
  utterancesRepo: "https://github.com/aldrinjenson/aldrinjenson.github.io"
  utterancesTheme: "github-dark"
  utterancesLabel: "comment"
  social:
    - id: github
      name: aldrinjenson
    - id: linkedin
      name: aldrinjenson
    - id: twitter
      name: aldrinjenson
    - id: medium
      name: aldrinjenson
    - id: rss
      name: "index.xml"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

canonifyURLs: true
